### ISSUE TITLE
Cannot capture RAW16 ASI6200MM Pro

### ISSUE THREAD

**Issue by haribostars** [stevemarple/python-zwoasi#20]
I have used the demo script made available and the RAW8 imaging works successfully however I am unable to capture RAW16 images, the bandwidth is set to 40 (minimum) and the output image file is set to .tiff. The exposure status indicates that the exposure is working (1) while iterating through the while loop, but returns failed (3) at the end of the exposure. The specific line in the demo script is "camera.capture(filename=filename)" and the lines from the __init__.py file are:

    def capture(self, initial_sleep=0.01, poll=0.01, buffer_=None,
                filename=None):
        """Capture a still image. Type :class:`numpy.ndarray`."""
        self.start_exposure()
        if initial_sleep:
            time.sleep(initial_sleep)
        while self.get_exposure_status() == ASI_EXP_WORKING:
            if poll:
                time.sleep(poll)
                print(self.get_exposure_status())
            pass
	    
        status = self.get_exposure_status()
        if status != ASI_EXP_SUCCESS:
            print(self.get_exposure_status())
            raise ZWO_CaptureError('Could not capture image', status)

I am running the code from ubuntu 20.04 and I have the camera connected via usb to my computer and it is also connected to an external power for cooling. Any help with resolving this issue would be greatly appreciated!

**Comment by zhoutman** [comment]
Hi,

I was curious if you were able to get it to work without using video mode. I am using the ASI6200MC Pro and run into the same issue as you with 16bit mono images.

Whenever I attempt to run your code for video capture I hit an issue where the code runs for a very long time. I have had to reset the kernel after force stopping the console every time I have attempted.

Thanks.

**Comment by asgaut** [comment]
I had a similar issue when capturing from an ASI120MM-S in 16 bit video mode. Have you ensured that `cat /sys/module/usbcore/parameters/usbfs_memory_mb` returns 200? I am setting this to 32 on a Raspberry Pi 3, and my C-code now works in this mode.

**Comment by haribostars** [comment]
> Hi,
> 
> I was curious if you were able to get it to work without using video mode. I am using the ASI6200MC Pro and run into the same issue as you with 16bit mono images.
> 
> Whenever I attempt to run your code for video capture I hit an issue where the code runs for a very long time. I have had to reset the kernel after force stopping the console every time I have attempted.
> 
> Thanks.

Hi zhoutman, 
I have not been able to get this working using the original capture method, just with the video capture. Ideally I'd rather not be using video mode but I have so far not been able to get it working any other way - if you have any luck with this please let me know! 

I added a sys.exit(0) which stops the code running completely once the image is taken, otherwise the camera cannot be re-initialised straight away. The other thing that I have found with the ASI6200MM Pro is that the external power source *is* required, even though they claim it is not. The video capture mode I gave above does not return an error if the camera isn't getting enough power, but it will of course fail to capture the image and the code will therefore run until interrupted. I have found the same issue when capturing via the gui, even when I am not operating the fans etc so my first recommendation would be to ensure the sensor is plugged into a power supply when you are trying to capture any images/video

**Comment by haribostars** [comment]
> I had a similar issue when capturing from an ASI120MM-S in 16 bit video mode. Have you ensured that `cat /sys/module/usbcore/parameters/usbfs_memory_mb` returns 200? I am setting this to 32 on a Raspberry Pi 3, and my C-code now works in this mode.

Hi asgaut, 
is this a fix for the long run time in video mode or to aid with capturing an image _without_ video mode? either way, `cat /sys/module/usbcore/parameters/usbfs_memory_mb` returns 16 for me, are you saying that it should be 200?

**Comment by asgaut** [comment]
I am not sure what issue it may fix.. At least the ASI Linux SDK has an udev rule (lib/asi.rules) file which sets this to 200:
```
ACTION=="add", ATTR{idVendor}=="03c3", RUN+="/bin/sh -c '/bin/echo 200 >/sys/module/usbcore/parameters/usbfs_memory_mb'"
# All ASI Cameras and filter wheels
SUBSYSTEMS=="usb", ATTR{idVendor}=="03c3", MODE="0666" 
```

I had problems with RAW16 in video streaming mode before, but I don't know if increasing this setting was the actual fix.

**Comment by zhoutman** [comment]
> 
> The other thing that I have found with the ASI6200MM Pro is that the external power source _is_ required, even though they claim it is not. The video capture mode I gave above does not return an error if the camera isn't getting enough power, but it will of course fail to capture the image and the code will therefore run until interrupted.

Well, that might be my problem then. I'll get to ordering a power cable and I'll let you know if I have better luck.

So far, I have had no luck in making RAW16 work with the ASI6200MM Pro. It's kind of strange to me that single image capture doesn't work but the video capture does.

**Comment by haribostars** [comment]
> > The other thing that I have found with the ASI6200MM Pro is that the external power source _is_ required, even though they claim it is not. The video capture mode I gave above does not return an error if the camera isn't getting enough power, but it will of course fail to capture the image and the code will therefore run until interrupted.
> 
> Well, that might be my problem then. I'll get to ordering a power cable and I'll let you know if I have better luck.
> 
> So far, I have had no luck in making RAW16 work with the ASI6200MM Pro. It's kind of strange to me that single image capture doesn't work but the video capture does.

Yes it is very odd, especially as I have had no issues using the capture function with 8RAW images. I'm sorry that I couldn't shed any more light on the matter, hopefully someone who has encountered and fixed the issue will see this thread!

**Comment by fommil** [comment]
Sorry to necro this old post, but I'm getting exactly the same error on the same line with an ASI1600MM Pro

```
Capturing a single 16-bit mono image
Traceback (most recent call last):
  File "/home/fommil/Projects/python-zwoasi/zwoasi/examples/zwoasi_demo.py", line 107, in <module>
    camera.capture(filename=filename)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/home/fommil/Projects/python-zwoasi/zwoasi/__init__.py", line 616, in capture
    raise ZWO_CaptureError('Could not capture image', status)
```

and I can confirm that the power supply is good because I'm able to capture 16 bit images no problem at all on my Windows machine using ASI Studio.

I first encountered this issue when trying to get 16 bit images out by calling the ASI libraries directly from python, but every time I call `ASISetROIFormat` with RAW16 I get a status 3 when a capture is about to finish.

I asked a question about this over at https://github.com/indilib/indi-3rdparty/issues/1098

because I noticed that my code can sometimes start to work after I run a capture in Ekos, so there must be **something** that indy is doing. Although I really need to confirm that more rigorously... although as far as I can tell indy is using the same API.

If anybody ever figured this out, I'd love to hear. As far as I can tell all my control values are as they should be, and I even do a couple of blink frames in my own code to try and flush out transient errors but it just doesn't want to go into RAW16 mode.

I'm on Debian 13 Linux and my `cat /sys/module/usbcore/parameters/usbfs_memory_mb` is 16, if that turns out to be relevant.

**Comment by fommil** [comment]
omg, setting

```
echo 32 | sudo tee /sys/module/usbcore/parameters/usbfs_memory_mb
```

means I get a 16 bit mono image, FINALLY! (then the demo fails later on when trying to set everything back to defaults on line 137 with an "Invalid control type" on 'CoolPowerPerc', which is obviously not settable)

How on earth did you figure that out @asgaut and why are you using 200? (200 also works for me, but 32 also worked so I went for caution)

I see in indi they set it to 1024 https://github.com/indilib/indi-3rdparty/blob/master/libasi/99-asi.rules ... which explains why the mere act of installing kstars was temporarily fixing my image capture!
