### ISSUE TITLE
"camera removed' error on start up

### ISSUE THREAD

**Issue by AstroKeith** [stevemarple/python-zwoasi#21]
I'm trying to run the demo program "as is" as a precursor to writing my own.
It finds the one camera i have (ZWO ASI120MM-S) with an ID of 0
then reports .....

Found one camera: ZWO ASI120MM-S
could not open camera 0
Traceback (most recent call last):
  File "/home/pi/Solver/demo.py", line 52, in <module>
    camera = asi.Camera(0)
  File "/home/pi/.local/lib/python3.7/site-packages/zwoasi/__init__.py", line 345, in __init__
    _open_camera(id_)
  File "/home/pi/.local/lib/python3.7/site-packages/zwoasi/__init__.py", line 39, in _open_camera
    raise zwo_errors[r]
zwoasi.ZWO_IOError: Camera removedcould not open camera 0
Traceback (most recent call last):
  File "/home/pi/Solver/demo.py", line 52, in <module>
    camera = asi.Camera(0)
  File "/home/pi/.local/lib/python3.7/site-packages/zwoasi/__init__.py", line 345, in __init__
    _open_camera(id_)
  File "/home/pi/.local/lib/python3.7/site-packages/zwoasi/__init__.py", line 39, in _open_camera
    raise zwo_errors[r]
zwoasi.ZWO_IOError: Camera removed

I've got the latest armv7 sdk from ZWO, running python3.7 on a RPi4.
(I'm not an experienced programmer)

I've tried USB2 & USB3
the ccd works fine with programs like ASIStudio, Ekos, etc

any ideas please?

**Comment by AstroKeith** [comment]
fixed it!
I hadn't installed asi.rules
(said I wasn't an experienced programmer!)

**Comment by AstroKeith** [comment]
all working nicely now - thanks to all the authors and contributors
